#!/usr/bin/env bash

# Defaults
if [ "$#" -ne 3 ]; then
  extraPython=$PYTHON_DATA_PLATFORM_2710  # This is set by ENV in the Dockerfile
  rootver=v6_06_02
  rootqual=e9:prof
else
  extraPython=$1
  rootver=$2
  rootqual=$3
 shift ; shift ; shift  # Conda's deactivate will see the options and get confused
fi

echo "Setting up Root $rootver -q $rootqual with extra python libraries at $extraPython"

# Deactivate Conda if necessary
if [ ! -z "$CONDA_DEFAULT_ENV" ]; then
  source /opt/miniconda/bin/deactivate
fi

# Setup our UPS products area
source /opt/products/setup
setup root "$rootver" -q "$rootqual"

# Add the extra Python library area
export PATH="$extraPython"/bin:$PATH
export LD_LIBRARY_PATH="$extraPython"/lib:$LD_LIBRARY_PATH
export PYTHONPATH="$extraPython"/lib/python2.7/site-packages:$PYTHONPATH
